<?php
/**
 * @var \Hiberus\Fernandez\Block\Index $block
 */
$marks = $block->getMarks();
$total = 0;
$mejorExamen = $block->getBestExam($marks);
//$media = $block->getMarkAverage($marks);
$aprobado = $block->getOK();
$segundoMejor = $block->getSecondBest($marks);
$terceroMejor = $block->getThirdBest($marks);
$max = $block->getMax();
$sumaNotas = 0;
$media = 0;
?>

<button id="toggle">Ocultar listado</button>
<button id="btn-alert">Nota más alta</button>

<div id="listado-notas">
    <h2 class="title">Listado de notas:</h2>

    <ul>
        <?php foreach ($marks as $mark): ?>
            <?php if ($total < $max || $max == null){ ?>
                <!--Para el ejercicio 13-->
                <?php if ( $mark->getIdExam() == $mejorExamen->getIdExam()  ||
                           $mark->getIdExam() == $segundoMejor->getIdExam() ||
                           $mark->getIdExam() == $terceroMejor->getIdExam() ){ ?>
                    <li class="mejores
                    <?php if ($mark->getMark() >= $aprobado){ ?>
                        aprobado">
                    <?php } else { ?>
                        suspenso">
                    <?php } ?>
                    <?php
                }else{
                    ?>
                    <?php if ($mark->getMark() >= $aprobado){ ?>
                        <li class="aprobado">
                    <?php } else { ?>
                        <li class="suspenso">
                    <?php }
                } ?>
                <?php echo $mark->getFirstName() . " "; ?>
                <?php echo $mark->getLastName() . " "; ?>
                <?php echo $mark->getMark(); ?>
                </li>
                <?php $sumaNotas = $sumaNotas + $mark->getMark();?>
                <?php $total++; ?>
            <?php } ?>
        <?php endforeach; ?>
    </ul>

    <?php $media = $sumaNotas/$total; ?>
    <p>
        <?php echo __('Total number of students: ') ?> <?php echo $total .  __('.')?> <br>
        <?php echo __('Mark average: ') ?> <?php echo number_format($media, 2) ?>
    </p>
</div>
<!--Aquí obtenemos la mejor nota en una etiqueta <p> para pasarsela a la función alert-->
<p id="nota" style="display: none">
    <?php echo $block->getBestExam($marks)->getMark(); ?>
</p>

<script type="text/javascript">
    require(['jquery','showjs', 'Magento_Ui/js/modal/alert'],function($){
        $(window).load(function() {

        });

        document.getElementById("btn-alert").addEventListener('click', function(){
            $('#nota').alert({
                title: $.mage.__('La mejor nota ha sido'),
                actions: {
                    always: function(){
                        location.reload();
                    }
                }
            });

        });

    });
</script>

<?php //Aquí va el custom Logger
$writer = new \Zend\Log\Writer\Stream(BP . '/var/log/hiberus_fernandez.log');
$logger = new \Zend\Log\Logger();
$logger->addWriter($writer);
$logger->info('Alumnos que se muestran: '. $total . '. Nota media: ' . number_format($media, 2));
?>
