<?php
/**
 * @var \Hiberus\Fernandez\Block\Index $block
 */
$marks = $block->getMarks();
$total = 0;
$mejorExamen = $block->getBestExam($marks);
$media = $block->getMarkAverage($marks);
$suspenso = 4.9;
?>

<button id="toggle">Ocultar listado</button>
<button id="btn-alert">Nota más alta</button>

<div id="listado-notas">
    <h2 class="title">Listado de notas:</h2>

    <ul>
    <?php foreach ($marks as $mark): ?>
        <!--Para el ejercicio 13-->
        <?php if ($mark->getIdExam() == $mejorExamen->getIdExam()){ ?>
            <li class="aprobado mejores">
        <?php
        }else{
            ?>
            <?php if ($mark->getMark() > $suspenso){ ?>
                <li class="aprobado">
            <?php } else { ?>
                <li class="suspenso">
        <?php     }
        } ?>
            <?php echo $mark->getFirstName() . " "; ?>
            <?php echo $mark->getLastName() . " "; ?>
            <?php echo $mark->getMark(); ?>
        </li>
            <?php $total++; ?>
    <?php endforeach; ?>
    </ul>

    <p>
        <?php echo __('Total number of students: ') ?> <?php echo $total .  __('.')?> <br>
        <?php echo __('Mark average: ') ?> <?php echo number_format($media, 2) ?>
    </p>
</div>
<!--Aquí obtenemos la mejor nota en una etiqueta <p> para pasarsela a la función alert-->
<p id="nota" style="display: none">
    <?php echo $block->getBestExam($marks)->getMark(); ?>
</p>

<script type="text/javascript">
    require(['jquery','showjs', 'Magento_Ui/js/modal/alert'],function($){
        $(window).load(function() {

        });

        document.getElementById("btn-alert").addEventListener('click', function(){
            $('#nota').alert({
                title: $.mage.__('La mejor nota ha sido'),
                actions: {
                    always: function(){
                        location.reload();
                    }
                }
            });

        });

    });
</script>
